### PR TITLE
Created Login Page

### LINKED ISSUE #40: Login Screen

### PR DESCRIPTION
**Pull request by stevnzhang**
Created a definitely secure login page.
---
Probably the most insecure login page you can find online, stores passwords in plaintext and just checks if the password inputted is the same as the plaintext one. Yikes.

Resolves #40

### CODE REVIEW

**Comment by emmayjiang** [comment]
steven Login.js doesn't exist in components in the code you pushed i cant run the code to review it T_T

**Review by emmayjiang — CHANGES_REQUESTED** [review]
Unable to resolve "./components/Login" from "App.js" - Login missing in pushed code?

**Comment by stevnzhang** [comment]
Added!

**Review by emmayjiang — APPROVED** [review]
LGTM o7

**Pull request merged**
